name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run code
        run: python ./main.py -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}}
